language: node_js
node_js:
 - "8"

cache:
  directories:
    - "node_modules"

install:
  - npm install
  - npm run build:prod

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  on:
    branch: master
